server:
  port: 8012
spring:
  datasource:    
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:log4jdbc:mysql://127.0.0.1:3306/kor_sb_2022?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
     username: korad
     password: kor123414
mybatis:
  type-aliases-package: com.jjh.exam.demo.vo